### ISSUE TITLE
Call to undefined function Phan\LanguageServer\pcntl_signal()

### ISSUE THREAD

**Issue by adammarton** [TysonAndre/vscode-php-phan#41] opened 2018-11-29 14:42 UTC
Yes, there's a chance that this is an issue with Phan itself, but otherwise Phan runs really well on the very same machine/code base/everything.

Env:

* Windows 10
* php-ast: 1.0.0

Debug output:
```
[Extension Host] Starting accepting connections on the language server (pid=281540)
[Extension Host] Error: Call to undefined function Phan\LanguageServer\pcntl_signal() in C:\Users\<username>\.vscode\extensions\tysonandre.php-phan-0.6.2\vendor\phan\phan\src\Phan\LanguageServer\LanguageServer.php:248
Stack trace:
#0 C:\Users\<username>\.vscode\extensions\tysonandre.php-phan-0.6.2\vendor\phan\phan\src\Phan\Phan.php(227): Phan\LanguageServer\LanguageServer::run(Object(Phan\CodeBase), Object(Closure), Array)
#1 C:\Users\<username>\.vscode\extensions\tysonandre.php-phan-0.6.2\vendor\phan\phan\src\phan.php(41): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#2 C:\Users\<username>\.vscode\extensions\tysonandre.php-phan-0.6.2\vendor\phan\phan\phan(2): require_once('C:\\Users\\<username>')
#3 {main}

(Phan 1.1.2 crashed due to an uncaught Throwable)
```

`config.php`:

```
<?php
return [
    'target_php_version' => '7.2',
    'directory_list' => [
        'classes'
    ],
    "exclude_analysis_directory_list" => [
        'vendor/'
    ],
];
```

Both globally installed and the packaged version of Phan runs perfectly fine, I only get these exceptions within VSCode.

Please let me know if you need more information.

Thanks,
Adam

**Comment by TysonAndre** [comment] 2018-11-29 15:08
A fix for this should be ready by the end of the day.

This was caused by a refactoring that called pcntl_signal to ensure that pcntl_wait was properly called to clean up dead processes - It should check that pcntl is available and/or needed

**Comment by adammarton** [comment] 2018-11-29 15:09
Who is awesome? You're awesome! ;)

Thanks for the quick reply!

**Comment by adammarton** [comment] 2018-11-29 15:38
@TysonAndre just checked out `90b72e` and it works like a charm, thanks!

**Closed** 2018-11-29 17:53 UTC
Labels: bug

**Comment by TysonAndre** [comment] 2018-11-29 17:59
0.6.3 has been published with a fix for this bug.
